/*
 * HistoryDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lfxfs.compents;

import java.util.List;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import com.lfxfs.AppView;
import com.lfxfs.dao.httpDao;
import com.lfxfs.model.HttpRequest;

/**
 *
 * @author  __USER__
 */
public class HistoryDialog extends javax.swing.JDialog {
	private httpDao httpDao =new httpDao();
	
	private AppView app;

	/** Creates new form HistoryDialog */
	public HistoryDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		app =(AppView)parent;
		initComponents();
		fullData();
		setLocationRelativeTo(getOwner()); 
	}
	
	private void fullData() {
		List<HttpRequest> httpRequests = httpDao.queryReqInfo();
		DefaultTableModel dtm = (DefaultTableModel) table_1.getModel();
		dtm.getDataVector().removeAllElements(); 
		for (int i = 0; i < httpRequests.size(); i++) {
			HttpRequest row = httpRequests.get(i);
			Vector v = new Vector();
			v.add("["+row.getCost()+"]");
			v.add(row);
//			v.add(row.getReqText());
			v.add(row.getReqDate());
			dtm.addRow(v);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		table_1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jTextField_url = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		table_1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null } },
				new String[] { "耗时[ms]", "请求地址", "请求时间" }){
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		
		});
		TableColumn firsetColumn = table_1.getColumnModel().getColumn(0);
		firsetColumn.setPreferredWidth(50);
		firsetColumn.setMaxWidth(50);
		firsetColumn.setMinWidth(50);
		TableColumn twoColumn = table_1.getColumnModel().getColumn(1);
		twoColumn.setPreferredWidth(50);
		twoColumn.setMaxWidth(500);
		twoColumn.setMinWidth(50);
		TableColumn threeColumn = table_1.getColumnModel().getColumn(2);
		threeColumn.setPreferredWidth(50);
		threeColumn.setMaxWidth(137);
		threeColumn.setMinWidth(50);
		table_1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				table_1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(table_1);

		jLabel1.setText("\u8bf7\u6c42\u5730\u5740");

		jTextField_url.setEditable(false);

		jLabel2.setText("\u8bf7\u6c42\u5165\u53c2");

		jLabel3.setText("\u8bf7\u6c42\u56de\u53c2");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setEditable(false);
		jScrollPane2.setViewportView(jTextArea1);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jTextArea2.setEditable(false);
		jScrollPane3.setViewportView(jTextArea2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				55,
																				55,
																				55)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField_url))
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								621,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				54,
																				54,
																				54)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jScrollPane3)
																						.addComponent(
																								jScrollPane2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								569,
																								Short.MAX_VALUE))))
										.addContainerGap(77, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												125,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(34, 34, 34)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField_url,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void table_1MouseClicked(java.awt.event.MouseEvent evt) {
		if(evt.getClickCount() ==1){
			int row = table_1.getSelectedRow();
			HttpRequest http = (HttpRequest)table_1.getValueAt(row, 1);
			jTextField_url.setText(http.getUrl());
			jTextArea1.setLineWrap(true);
			jTextArea2.setLineWrap(true);
			jTextArea1.setText(http.getReqText());
			jTextArea2.setText(http.getRspText());
		}
		if(evt.getClickCount() ==2){
			int row = table_1.getSelectedRow();
			HttpRequest http = (HttpRequest)table_1.getValueAt(row, 1);
			app.textField_url.setText(http.getUrl());
			app.textArea_reqText.setText(http.getReqText());
			app.textArea_rspText.setText(http.getRspText());
			dispose();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				HistoryDialog dialog = new HistoryDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField_url;
	private javax.swing.JTable table_1;
	// End of variables declaration//GEN-END:variables

}