/*
 * PostMan.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lfxfs;

import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import com.al.angel.invoke.http.HttpInvoke;
import com.al.angel.invoke.http.HttpResponse;
import com.lfxfs.dao.httpDao;
import com.lfxfs.model.HttpRequest;

/**
 *
 * @author  __USER__
 */
public class PostMan extends javax.swing.JFrame {

	private static final String ENCODING = "UTF-8";
	private httpDao httpDao = new httpDao();

	/** Creates new form PostMan */
	public PostMan() {
		initComponents();
		this.setLocationRelativeTo(this);
		this.fullHttpReq();
	}

	private void fullHttpReq() {
		List<HttpRequest> lists = httpDao.queryReqInfo();
		if (lists.size() > 0) {
			DefaultListModel dlm = new DefaultListModel();
			for (int i = 0; i < lists.size(); i++) {
				dlm.add(i, lists.get(i));
			}
			this.j_list.setModel(dlm);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {		
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		j_list = new javax.swing.JList();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jt_url = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jt_httpRequestText = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jt_htttpRespText = new javax.swing.JTextArea();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("post\u7b80\u5355\u5de5\u5177");
		
		j_list.addMouseListener(new java.awt.event.MouseAdapter() {
		public void mousePressed(java.awt.event.MouseEvent evt) {
		j_listMousePressed(evt);
		}
		});
		jScrollPane1.setViewportView(j_list);
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(jPanel1Layout.createSequentialGroup()
		.addContainerGap()
		.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(jPanel1Layout.createSequentialGroup()
		.addContainerGap()
		.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
		.addContainerGap())
		);
		
		jLabel1.setText("\u5730\u5740");
		
		jButton1.setText("\u8bf7\u6c42");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
		jButton1ActionPerformed(evt);
		}
		});
		
		jLabel2.setText("\u8bf7\u6c42\u5185\u5bb9");
		
		jt_httpRequestText.setColumns(20);
		jt_httpRequestText.setRows(5);
		jScrollPane2.setViewportView(jt_httpRequestText);
		
		jLabel3.setText("\u8fd4\u56de\u5185\u5bb9");
		
		jt_htttpRespText.setColumns(20);
		jt_htttpRespText.setRows(5);
		jScrollPane3.setViewportView(jt_htttpRespText);
		
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
		jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(jPanel2Layout.createSequentialGroup()
		.addContainerGap()
		.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(jPanel2Layout.createSequentialGroup()
		.addComponent(jLabel1)
		.addGap(31, 31, 31)
		.addComponent(jt_url, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
		.addGap(44, 44, 44)
		.addComponent(jButton1)
		.addGap(67, 67, 67))
		.addGroup(jPanel2Layout.createSequentialGroup()
		.addComponent(jLabel2)
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
		.addContainerGap())
		.addGroup(jPanel2Layout.createSequentialGroup()
		.addComponent(jLabel3)
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
		.addContainerGap())))
		);
		jPanel2Layout.setVerticalGroup(
		jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(jPanel2Layout.createSequentialGroup()
		.addContainerGap()
		.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		.addComponent(jLabel1)
		.addComponent(jButton1)
		.addComponent(jt_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		.addGap(18, 18, 18)
		.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addComponent(jLabel2)
		.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		.addGap(29, 29, 29)
		.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addComponent(jLabel3)
		.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
		.addContainerGap())
		);
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addGroup(layout.createSequentialGroup()
		.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
		.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		);
		layout.setVerticalGroup(
		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		
		pack();
	}// </editor-fold>

	//GEN-END:initComponents
	private void j_listMousePressed(java.awt.event.MouseEvent evt) {
		HttpRequest req = (HttpRequest) this.j_list.getSelectedValue();
		this.jt_htttpRespText.setLineWrap(true);
		this.jt_httpRequestText.setLineWrap(true);
		this.jt_url.setText(req.getUrl());
		this.jt_httpRequestText.setText(req.getReqText());
		this.jt_htttpRespText.setText(req.getRspText());

	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			this.jt_htttpRespText.setLineWrap(true);
			this.jt_httpRequestText.setLineWrap(true);
			HttpRequest req = new HttpRequest();
			String url = this.jt_url.getText().trim();
			String reqText = this.jt_httpRequestText.getText().trim();
			
			HttpResponse resp = HttpInvoke.sendRequest(url, null, reqText,
					3600, this.ENCODING);
			String respText = resp.getContent().trim();
			this.jt_htttpRespText.setText(respText);
			req.setUrl(url);
			req.setReqText(reqText);
			req.setRspText(respText);
			httpDao.saveReqInfo(req);

			this.fullHttpReq();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PostMan().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JList j_list;
	private javax.swing.JTextArea jt_httpRequestText;
	private javax.swing.JTextArea jt_htttpRespText;
	private javax.swing.JTextField jt_url;
	// End of variables declaration//GEN-END:variables

}